### ISSUE TITLE
弱网环境下边缘计算单节点Linux服务器监控

### ISSUE THREAD

**Issue by timzaak** [timzaak/blog#124]
首先想到的方案是 Prometheus 的 node-exporter + Promethus。
但 node-exporter 本地文件导出格式并不适合人观看，远程要么走Promethus 拉信息，要么走 `Pushgateway` 中间件。 
无法满足我们的需求：
1. 本地可简单观看近几个小时的数据，要落盘，方便人可阅读。
2. 弱网推送小规模数据（允许丢包）。

需要我们自行实现，可参考：[metron](https://github.com/THISUXHQ/metron/) 来做，信息采集走 [sysinfo](https://github.com/GuillaumeGomez/sysinfo)。
客户端：
1. 用日志框架落盘，比较方便设置格式和滚动。
2. 走 MQTT 协议推送， QoS：0（至多一次）。

服务器端：写MQTT消息订阅插件，将数据再次转发至 Promethus进行存储。

### 客户端：
配置：
```toml
[mqtt]
url='mqtt://???'
clientId=''
password=''

[collector]
interval='20s'
metrics=['参考 node-exporter']
reserve='60m'
```
